import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CSPostHogProvider } from "@/app/analytics/posthogProvider";
import { AxiomWebVitals } from "next-axiom";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "400 600 950",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <CSPostHogProvider>
            <html lang="en">
                <body className={`${geistSans.variable} bg-background text-foreground antialiased`}>
                    <AxiomWebVitals />
                    {children}
                </body>
            </html>
        </CSPostHogProvider>
    );
}
